services:
  - name: terminal
    plan: nano
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    egress:
      enabled: true
      toCIDRs:
        - range: 1.1.1.1/32
          port: 53
          protocol: UDP
      toFQDNs:
        - pattern: '*.locaweb.com.br'
          port: 443
          protocol: TCP
      toFQDNs:
        - pattern: '*.ubuntu.com'
    allowToServices:
      - namespace: utilities
        name: echo
  - name: wp
    ingress:
      enabled: true
      hosts:
        - www5.giba.tech
    image: wordpress:php8.3-apache
    port: 80
    plan: small
    dbConnections:
      - name: wp-db
        type: pxc
        envVarMappings:
          WORDPRESS_DB_NAME: database
          WORDPRESS_DB_HOST: host
          WORDPRESS_DB_USER: user
          WORDPRESS_DB_PASSWORD: password
      - name: memcached
        type: dragonfly
        envVarMappings:
          GIBA_HOST: host
          GIBA_PASSWORD: password
          GIBA_URL: url
    mountVolumes:
      - name: wp-vol
        path: /var/www/html
dbServers:
  - name: wp-db
    type: pxc
    version: "8.0"
    plan: small
    size: 60Gi
    pause: false
  - name: memcached
    type: dragonfly
    replicas: 2
    plan: micro
    memcached:
      enabled: true
volumes:
  - name: wp-vol
    size: 100Gi
