configmaps:
  - name: magento
    data:
      MAGENTO_ELASTICSEARCH_PORT_NUMBER: "9200"
      MAGENTO_ELASTICSEARCH_USE_HTTPS: "yes"
      MAGENTO_ELASTICSEARCH_ENABLE_AUTH: "yes"
      MAGENTO_EXTRA_INSTALL_ARGS: "--verbose"
      BITNAMI_DEBUG: "true"

services:
  - name: magento
    plan: micro
    image: bitnami/magento:2.4.7
    egress:
      enabled: true
    mountVolumes:
      - name: magento
        path: /bitnami/magento
    envVarsFrom:
      configMaps:
        - name: magento
        # na ausência de mappings, chaves do segredo são mapeadas diretamente para nomes das variáveis de ambiente
      searches:
        - name: magento
          type: elasticsearch
          mappings:
            MAGENTO_ELASTICSEARCH_HOST: ELASTICSEARCH_HOST
            MAGENTO_ELASTICSEARCH_USER: ELASTICSEARCH_USER
            MAGENTO_ELASTICSEARCH_PASSWORD: ELASTICSEARCH_PASSWORD
      dbServers:
        - name: magento
          type: pxc
          mappings:
            MAGENTO_DATABASE_HOST: DB_HOST
            MAGENTO_DATABASE_NAME: DB_NAME
            MAGENTO_DATABASE_USER: DB_USER
            MAGENTO_DATABASE_PASSWORD: DB_PASSWORD

dbServers:

  - name: magento
    type: pxc
    version: "8.0"
    plan: micro
    size: 90Gi

searches:
  - name: magento
    type: elasticsearch
    version: "8.15.3"
    nodes:
      master:
        replicas: 3
        plan: medium
        size: 80Gi
      data:
        replicas: 3
        plan: large
        size: 160Gi
    dashboard:
      enabled: true
      replicas: 1
      plan: small

volumes:
  - name: magento
    size: 100Gi