configmaps:
  - name: mapa
    data:
      nome: Giba
      empresa: LWSA

  - name: outromapa
    data:
      foo: bar

secrets:
  - name: segredo
    namespace: utilities
    data:
      chave: AgAet5yO4BylNhInbf0s20rUOmlw2F8Ik86Y4OMsqgBXHquYw5tevTLXRDopO6bRWXsBlOmGdSgpP2SyECWesGx1f/RM/YkobIYXGg1KbDPwBNW7h3m9ho2N7oTtrzUveprhyL4YGuD65ubeF1HP9S/8higfHxRPp/QAiy6P4kGppMegVmAETMHrfHSEFqLs0uFDzWJQ0OdEMTtbJG8uV41ORUpVgPG6Z0MmKwmM9dB50ppSBvAhnBf9L2RbYPMrGw4dUhsHDfxwreXWo/tdjjEU3fWPB/WUk/ppRC2G4z50tgK+n5x4dzJwzGT13uRm+9x80COaq45jQt56GcSwspsMQ3GX9zzOUEDxoemXGjMaBy65GbFFC2vBQM4EdxgeZOSKtMrbtB8UGxldeFJ1dm171QzlNJXzvrS9cn7PhRWXH0iylSKdNC2R0X7GopJI68JQAPeCmJ6EAGGAmcZrxoZR3vvApOpNBCz9am1TFdSAfuUkGPTwZHNbyVYPQ3U97guNOiFzvbUupNgMwpGsvxa6iHv+ui6j5ZPtNUkFcmOaH27+ZUplOOD0nY33RDpsdv67S8MX4qB+rvA2AEDfTZ2z7phApn+htue7ktSMt9jCzhinCjNBmNexi6FbkXAsoo5cqgM4geO2gzBneF+vgqLmcnBSOyjKOsiAg4DpTrV67PpsbQ9GXnSY0ByA5FL8u55EYZvU5CwdJc8mmz0NPYvWGLw=

services:
  - name: console
    plan: micro
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    egress:
      enabled: true
      toCIDRs:
        - range: 1.1.1.1/32
          port: 53
          protocol: UDP
      toFQDNs:
        - pattern: '*.locaweb.com.br'
          port: 443
          protocol: TCP
        - pattern: '*.ubuntu.com'
    envVarsFrom:
      secrets:
        - name: segredo
          mappings:
            CHAVE: chave
      configMaps:
        - name: mapa
          mappings:
            NAME: nome
            COMPANY: empresa
        - name: outromapa

  - name: echo
    plan: nano
    ingress:
      enabled: true
    image: cilium/echoserver

  - name: pgadmin
    ingress:
      enabled: true
    image: dpage/pgadmin4:8.5
    plan: micro
    envVars:
      PGADMIN_DEFAULT_EMAIL: gilberto.mautner@locaweb.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "10000"

dbServers:
  - name: mydb
    replicas: 3
    type: pxc
    version: "8.0"
    plan: small
    size: 60Gi
    expose:
      enabled: true
    # quando true, desliga banco, sem apagar dados. Serve para economizar recursos quando não precisa
    pause: false

  - name: pg
    type: cnpg
    version: "16"
    plan: micro
    size: 90Gi