services:
  - name: console
    plan: micro
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    dbConnections:
      - name: hibrido
        type: dragonfly

  - name: webserver
    image: registry.k8s.io/hpa-example
    plan: nano
    port: 80
    ingress:
      enabled: true
    minReplicas: 1
    maxReplicas: 10

  - name: echo
    plan: nano
    ingress:
      enabled: true
      hosts:
        - www3.giba.tech
    image: cilium/echoserver
    allowFromServices:
      - namespace: wordpress
        name: terminal
  - name: myphp
    ingress:
      enabled: true
    image: gmautner/myphp:latest
    plan: nano
    minReplicas: 1
    maxReplicas: 8
    dbConnections:
      - name: mydb
        type: pxc
        envVarMappings:
          MY_DB_HOST: host
          MY_DB_USER: user
          MY_DB_PASSWORD: password
          VAR_BANCO: database
  - name: pgadmin
    ingress:
      enabled: true
    image: dpage/pgadmin4:8.5
    plan: micro
    envVars:
      PGADMIN_DEFAULT_EMAIL: gilberto.mautner@locaweb.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "10000"
dbServers:
  - name: hibrido
    type: dragonfly
    plan: nano
    passwordAuth:
      enabled: true
    memcached:
      enabled: true
  - name: mydragongly
    type: dragonfly
    plan: nano
    passwordAuth:
      enabled: true
    replicas: 2
    snapshot:
      enabled: true
      size: 2Gi
  - name: memcached
    type: dragonfly
    plan: micro
    memcached:
      enabled: true
  - name: mydb
    replicas: 3
    type: pxc
    version: "8.0"
    plan: small
    size: 60Gi
    expose:
      enabled: true
  - name: meucnpg2
    type: cnpg
    version: "15"
    plan: micro
    size: 90Gi
  - name: copypg
    type: cnpg
    version: "15"
    plan: micro
    replicas: 3
    size: 90Gi
  - name: io2
    type: pxc
    version: "8.0"
    plan: 2xlarge
    size: 380Gi
    expose:
      enabled: true
  - name: testdb
    type: pxc
    version: "8.0"
    size: 30Gi
    plan: small
  - name: cnpg32
    type: cnpg
    version: "15"
    size: 380Gi
    plan: 2xlarge