configmaps:
  - name: mapa
    data:
      nome: Giba
      empresa: LWSA

  - name: outromapa
    data:
      foo: bar

secrets:
  - name: segredo
    namespace: utilities
    data:
      chave: AgAet5yO4BylNhInbf0s20rUOmlw2F8Ik86Y4OMsqgBXHquYw5tevTLXRDopO6bRWXsBlOmGdSgpP2SyECWesGx1f/RM/YkobIYXGg1KbDPwBNW7h3m9ho2N7oTtrzUveprhyL4YGuD65ubeF1HP9S/8higfHxRPp/QAiy6P4kGppMegVmAETMHrfHSEFqLs0uFDzWJQ0OdEMTtbJG8uV41ORUpVgPG6Z0MmKwmM9dB50ppSBvAhnBf9L2RbYPMrGw4dUhsHDfxwreXWo/tdjjEU3fWPB/WUk/ppRC2G4z50tgK+n5x4dzJwzGT13uRm+9x80COaq45jQt56GcSwspsMQ3GX9zzOUEDxoemXGjMaBy65GbFFC2vBQM4EdxgeZOSKtMrbtB8UGxldeFJ1dm171QzlNJXzvrS9cn7PhRWXH0iylSKdNC2R0X7GopJI68JQAPeCmJ6EAGGAmcZrxoZR3vvApOpNBCz9am1TFdSAfuUkGPTwZHNbyVYPQ3U97guNOiFzvbUupNgMwpGsvxa6iHv+ui6j5ZPtNUkFcmOaH27+ZUplOOD0nY33RDpsdv67S8MX4qB+rvA2AEDfTZ2z7phApn+htue7ktSMt9jCzhinCjNBmNexi6FbkXAsoo5cqgM4geO2gzBneF+vgqLmcnBSOyjKOsiAg4DpTrV67PpsbQ9GXnSY0ByA5FL8u55EYZvU5CwdJc8mmz0NPYvWGLw=

services:
  - name: console
    plan: micro
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    egress:
      enabled: true
      toCIDRs:
        - range: 1.1.1.1/32
          port: 53
          protocol: UDP
      toFQDNs:
        # na ausência de port/protocol, conexões para qualquer porta e protocolo são permitidas
        - pattern: '*.ubuntu.com'
        - host: 'www.locaweb.com.br'
          port: 443
          protocol: TCP
    envVarsFrom:
      secrets:
        - name: segredo
          mappings:
            CHAVE: chave
      configMaps:
        - name: mapa
          mappings:
            NAME: nome
            COMPANY: empresa
        # na ausência de mappings, chaves do segredo são mapeadas diretamente para nomes das variáveis de ambiente
        - name: outromapa
      searches:
        - name: mysearch
          type: elasticsearch
          mappings:
            ES_HOST: ELASTICSEARCH_HOST
            ES_PORT: ELASTICSEARCH_PORT
            ES_USER: ELASTICSEARCH_USER
            ES_PASSWORD: ELASTICSEARCH_PASSWORD
            ES_URI: ELASTICSEARCH_URL

  - name: echo
    plan: nano
    ingress:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
    image: cilium/echoserver

  - name: pgadmin
    ingress:
      enabled: true
    image: dpage/pgadmin4:8.5
    plan: micro
    envVars:
      PGADMIN_DEFAULT_EMAIL: gilberto.mautner@locaweb.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "10000"

dbServers:
  - name: mydb
    replicas: 1
    type: pxc
    version: "8.0"
    plan: large
    size: 200Gi
    expose:
      enabled: true
    # quando true, desliga banco, sem apagar dados. Serve para economizar recursos quando não precisa
    pause: false

  # - name: mydb-copy
  #   replicas: 1
  #   type: pxc
  #   version: "8.0"
  #   plan: large
  #   size: 200Gi
  #   restoreFrom:
  #     name: mydb

  - name: newdb
    replicas: 1
    type: pxc
    version: "8.0"
    plan: 2xlarge
    size: 200Gi
    expose:
      enabled: true

  - name: pg
    type: cnpg
    version: "16"
    plan: micro
    size: 90Gi
    expose:
      enabled: true
    pause: false

  # - name: pg-copy
  #   type: cnpg
  #   version: "16"
  #   plan: micro
  #   size: 90Gi
  #   restoreFrom:
  #     name: pg

searches:
  - name: mysearch
    type: elasticsearch
    version: "8.15.2"
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
    nodes:
      master:
        replicas: 3
        plan: medium
        size: 80Gi
      data:
        replicas: 3
        plan: large
        size: 160Gi
    dashboard:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
      replicas: 1
      plan: small