services:

  - name: console
    plan: micro
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    egress:
      enabled: true
      toCIDRs:
        - range: 1.1.1.1/32
          port: 53
          protocol: UDP
      toFQDNs:
        - pattern: '*.locaweb.com.br'
          port: 443
          protocol: TCP
        - pattern: '*.ubuntu.com'

  - name: echo
    plan: nano
    ingress:
      enabled: true
    image: cilium/echoserver

  - name: pgadmin
    ingress:
      enabled: true
    image: dpage/pgadmin4:8.5
    plan: micro
    envVars:
      PGADMIN_DEFAULT_EMAIL: gilberto.mautner@locaweb.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "10000"

dbServers:

  - name: mydb
    replicas: 3
    type: pxc
    version: "8.0"
    plan: small
    size: 60Gi
    expose:
      enabled: true
    # quando true, desliga banco, sem apagar dados. Serve para economizar recursos quando não precisa
    pause: false

  - name: pg
    type: cnpg
    version: "16"
    plan: micro
    size: 90Gi