# Horizontal Pod Autoscaler
# Aumenta/dimunui replicas com gatilho de 200% requested CPU (dimensionado de acordo com overselling)
# Services aceitam `command` e `args` assim como containers. O comando inserido serve para container não ser encerrado
# Instruções: shell into console e execute "while sleep 0.01; do wget -q -O- http://webserver; done" digitando Ctrl-C para interromper
# Observe aumento/diminuição de replicas durante a execução
#
# Demonstramos também como abrir comunicação com outros serviços. Usar em conjunto com o exemplo no namespace "portal"
# Instruções: shell into console e execute "wget http://wp.portal" com e sem a configuração comentada abaixo
# (observe que a config. correspondente `allowFromServices` já foi colocada no blueprint do portal)

services:
  - name: console
    image: busybox
    plan: small
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    allowToServices:
      - namespace: portal
        name: wp
  - name: webserver
    image: registry.k8s.io/hpa-example
    plan: nano
    port: 80
    minReplicas: 1
    maxReplicas: 10
