services:
  - name: nextcloud
    plan: micro
    port: 80
    ingress:
      enabled: true
    image: nextcloud:29.0
    envVars:
      POSTGRES_DB: admin
    mountVolumes:
      - name: nextcloud-vol
        path: /var/www/html
    dbConnections:
      - name: nextcloud-db
        type: cnpg
        envVarMappings:
          POSTGRES_HOST: host
          POSTGRES_READ: host_read
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          CONNECTION_STRING: url
      - name: redis
        type: dragonfly
        envVarMappings:
          REDIS_HOST: host
          REDIS_HOST_PASSWORD: password

dbServers:
  - name: nextcloud-db
    type: cnpg
    version: "15"
    plan: micro
    size: 50Gi
    expose:
      enabled: true

  - name: redis
    type: dragonfly
    plan: micro
    passwordAuth:
      enabled: true

volumes:
  - name: nextcloud-vol
    size: 50Gi