services:
  - name: wekan
    plan: micro
    port: 8080
    ingress:
      enabled: true
    image: wekanteam/wekan:v7.72
    mountVolumes:
      - name: wekan-files
        path: /dados
    envVars:
      WRITABLE_PATH: "/dados"
      ROOT_URL: "https://kanban-wekan.global.prod.demo.ingress.sh"
    envVarsFrom:
      dbServers:
        - name: wekandb
          type: ferretdb
          mappings:
            MONGO_URL: MONGODB_URI

dbServers:
  - name: wekandb
    type: ferretdb
    version: "17"
    plan: micro
    size: 100Gi
    replicas: 3

  # - name: wekan-mongodb
  #   type: psmdb
  #   plan: micro
  #   size: 100Gi
  #   replicas: 3
  #   pause: false
  #   expose:
  #     enabled: false
  #     sourceRanges:
  #       - "189.0.0.0/8"
  #       - "186.0.0.0/8"
  #       - "187.0.0.0/8"
  #       - "185.0.0.0/8"
  #       - "177.0.0.0/8"

volumes:
  - name: wekan-files
    size: 100Gi